"""
schemas.py — Pydantic v2 request and response models.

All response models use `model_config = ConfigDict(from_attributes=True)`
so they can be built directly from SQLAlchemy ORM instances with
`MySchema.model_validate(orm_obj)`.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from app.models import GrievanceCategory, GrievanceStatus, ProjectStatus, UserRole


# ── User ──────────────────────────────────────────────────────────────────────

class UserOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    name: str
    phone: str
    role: UserRole
    created_at: datetime


# ── Resolution Evidence ───────────────────────────────────────────────────────

class ResolutionEvidenceOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    grievance_id: str
    officer_id: Optional[str] = None
    proof_image_url: Optional[str] = None
    comments: str
    resolved_at: datetime


# ── Grievance ─────────────────────────────────────────────────────────────────

class GrievancePublic(BaseModel):
    """Full grievance detail — returned for single-item and list endpoints."""

    model_config = ConfigDict(from_attributes=True)

    id: str
    title: str
    description: str
    category: GrievanceCategory
    status: GrievanceStatus
    priority_score: int
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    address: Optional[str] = None
    image_url: Optional[str] = None
    audio_url: Optional[str] = None
    is_duplicate: bool
    parent_grievance_id: Optional[str] = None
    upvote_count: int
    citizen_id: Optional[str] = None
    created_at: datetime
    updated_at: datetime
    evidence: list[ResolutionEvidenceOut] = Field(default_factory=list)


class GrievanceCreateResponse(BaseModel):
    """Returned immediately after a successful grievance submission."""

    model_config = ConfigDict(from_attributes=True)

    id: str
    title: str
    description: str
    category: GrievanceCategory
    status: GrievanceStatus
    priority_score: int
    is_duplicate: bool
    parent_grievance_id: Optional[str] = None
    upvote_count: int
    # urgency_summary is generated by the AI classifier; shown in the UI
    urgency_summary: Optional[str] = None
    created_at: datetime


class ResolveGrievanceRequest(BaseModel):
    """Body for the resolve endpoint (comments field is always required)."""

    comments: str = Field(..., min_length=1, description="Officer's resolution notes.")
    officer_id: Optional[str] = Field(
        default=None, description="Officer user ID (optional for demo)."
    )


# ── Stats ─────────────────────────────────────────────────────────────────────

class CategoryCount(BaseModel):
    category: str
    count: int


class StatsOut(BaseModel):
    total_reported: int
    auto_deduplicated: int
    resolved_percent: float
    by_category: list[CategoryCount]


# ── Participatory Budgeting ───────────────────────────────────────────────────

class ProjectOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    title: str
    description: str
    budget_allocated: float
    target_votes: int
    current_votes: int
    category: str
    status: ProjectStatus
    created_at: datetime


class VoteRequest(BaseModel):
    citizen_id: str = Field(..., description="ID of the citizen casting the vote.")


# ── WebSocket Events ──────────────────────────────────────────────────────────
# These are not Pydantic models per-se; they are plain dicts broadcast over WS.
# Documented here for reference:
#
# new_grievance:    {"event": "new_grievance",    "data": GrievancePublic.dict()}
# grievance_resolved: {"event": "grievance_resolved","data": GrievancePublic.dict()}
# project_vote:     {"event": "project_vote",     "data": ProjectOut.dict()}
