import { GrievanceTicket, MunicipalDeptCode, MUNICIPAL_DEPARTMENTS } from "./grievance";

export function getInitialSeedTickets(): GrievanceTicket[] {
  const now = new Date();
  const getDateAgo = (hoursAgo: number) => new Date(now.getTime() - hoursAgo * 3600 * 1000).toISOString();
  const getFutureDate = (hoursAhead: number) => new Date(now.getTime() + hoursAhead * 3600 * 1000).toISOString();

  return [
    // ── Multi-Ward Waterlogging Cluster (triggers Commissioner Cluster Alert) ──
    {
      id: "TKT-2026-0001",
      citizenId: "cit-101",
      citizenName: "Rohit Pattnaik",
      citizenPhone: "+919437012345",
      title: "Drainage blockage near Laxmi Sagar Main Road",
      description: "Severe main drain blockage causing toxic water overflow onto the main market road. Vehicles getting stuck.",
      mediaUrls: ["https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=800&auto=format&fit=crop&q=60"],
      latitude: 20.2610,
      longitude: 85.8460,
      addressText: "Laxmi Sagar Main Road, Ward 3, Bhubaneswar",
      landmark: "Near Laxmi Sagar Police Station",
      wardId: "BMC Ward 3",
      wardNumber: 3,
      departmentCode: "water_supply",
      assignedOfficerName: "Suresh Das",
      assignedOfficerRole: "Senior Hydro Engineer",
      status: "IN_PROGRESS",
      priority: "CRITICAL",
      createdAt: getDateAgo(12),
      updatedAt: getDateAgo(2),
      slaDeadlineAt: getFutureDate(36),
      reopenedCount: 0,
      supporterIds: ["cit-101", "cit-105", "cit-109", "cit-112"],
      upvoteCount: 14,
    },
    {
      id: "TKT-2026-0002",
      citizenId: "cit-102",
      citizenName: "Ananya Das",
      citizenPhone: "+919437112346",
      title: "Severe storm drain overflow at Cuttack Road",
      description: "Waterlogging spreading over 200m on Cuttack Road near Satya Nagar crossing due to choked storm channels.",
      mediaUrls: ["https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=800&auto=format&fit=crop&q=60"],
      latitude: 20.3009,
      longitude: 85.8546,
      addressText: "Cuttack Road crossing, Satya Nagar, Ward 7, Bhubaneswar",
      landmark: "Opposite AG Office Flyover",
      wardId: "BMC Ward 7",
      wardNumber: 7,
      departmentCode: "water_supply",
      status: "NEW",
      priority: "HIGH",
      createdAt: getDateAgo(5),
      updatedAt: getDateAgo(5),
      slaDeadlineAt: getFutureDate(43),
      reopenedCount: 0,
      supporterIds: ["cit-102", "cit-114", "cit-118"],
      upvoteCount: 18,
    },
    {
      id: "TKT-2026-0003",
      citizenId: "cit-103",
      citizenName: "Vikram Mohanty",
      citizenPhone: "+919437312347",
      title: "Sewer water backflow near Old Town Market",
      description: "Underground sewerage pipeline ruptured. Foul smelling water submerging pedestrian walkways.",
      mediaUrls: ["https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&auto=format&fit=crop&q=60"],
      latitude: 20.2456,
      longitude: 85.8341,
      addressText: "Old Town Market Square, Ward 11, Bhubaneswar",
      landmark: "Near Bindu Sagar Tank Entrance",
      wardId: "BMC Ward 11",
      wardNumber: 11,
      departmentCode: "water_supply",
      status: "NEW",
      priority: "CRITICAL",
      createdAt: getDateAgo(3),
      updatedAt: getDateAgo(3),
      slaDeadlineAt: getFutureDate(45),
      reopenedCount: 0,
      supporterIds: ["cit-103", "cit-120", "cit-122", "cit-125", "cit-129"],
      upvoteCount: 22,
    },
    {
      id: "TKT-2026-0004",
      citizenId: "cit-104",
      citizenName: "Siddharth Swain",
      citizenPhone: "+919437412999",
      title: "Stagnant waterlogging near Patia Big Bazaar",
      description: "Drainage outlet blocked by construction debris. 1.5ft deep standing water inundating residential gates.",
      mediaUrls: ["https://images.unsplash.com/photo-1584467735871-8e85353a8413?w=800&auto=format&fit=crop&q=60"],
      latitude: 20.3476,
      longitude: 85.8138,
      addressText: "Patia Infocity Road, Ward 15, Bhubaneswar",
      landmark: "Near KIIT Square",
      wardId: "BMC Ward 15",
      wardNumber: 15,
      departmentCode: "water_supply",
      assignedOfficerName: "Suresh Das",
      assignedOfficerRole: "Field Superintendent",
      status: "IN_PROGRESS",
      priority: "HIGH",
      createdAt: getDateAgo(18),
      updatedAt: getDateAgo(1),
      slaDeadlineAt: getFutureDate(30),
      reopenedCount: 0,
      supporterIds: ["cit-104", "cit-130", "cit-131", "cit-132"],
      upvoteCount: 12,
    },

    // ── Roads & Potholes Ticket ──
    {
      id: "TKT-2026-0005",
      citizenId: "cit-105",
      citizenName: "Subhashree Nayak",
      citizenPhone: "+919437512349",
      title: "Deep crater pothole opposite ITER College Main Gate",
      description: "Huge 4-foot wide asphalt crater causing daily accidents for college students and commuters.",
      mediaUrls: ["https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=800&auto=format&fit=crop&q=60"],
      latitude: 20.2506,
      longitude: 85.7868,
      addressText: "Jagamara Road, Ward 12, Bhubaneswar",
      landmark: "Opposite ITER College Gate 1",
      wardId: "BMC Ward 12",
      wardNumber: 12,
      departmentCode: "roads_potholes",
      assignedOfficerName: "Rajesh Mohanty",
      assignedOfficerRole: "Junior Engineer (JE Roads)",
      status: "ASSIGNED",
      priority: "HIGH",
      createdAt: getDateAgo(20),
      updatedAt: getDateAgo(4),
      slaDeadlineAt: getFutureDate(52),
      reopenedCount: 0,
      supporterIds: ["cit-105", "cit-140", "cit-141"],
      upvoteCount: 9,
    },

    // ── Street Lights Ticket (For Citizen Verification Demo) ──
    {
      id: "TKT-2026-0006",
      citizenId: "cit-106",
      citizenName: "Deepak Tripathy",
      citizenPhone: "+919437612350",
      title: "Broken street light near Khandagiri Square",
      description: "Entire 300-meter stretch dark for 3 consecutive nights. Major safety hazard for pedestrians.",
      mediaUrls: ["https://images.unsplash.com/photo-1509114397022-ed747cca3f65?w=800&auto=format&fit=crop&q=60"],
      latitude: 20.2506,
      longitude: 85.7868,
      addressText: "Khandagiri Caves Road, Ward 12, Bhubaneswar",
      landmark: "Near Khandagiri Tourist Police Post",
      wardId: "BMC Ward 12",
      wardNumber: 12,
      departmentCode: "street_lights",
      assignedOfficerName: "Anita Behera",
      assignedOfficerRole: "Electrical Inspector",
      status: "RESOLVED",
      priority: "MEDIUM",
      createdAt: getDateAgo(30),
      updatedAt: getDateAgo(2),
      slaDeadlineAt: getDateAgo(6),
      resolutionProof: {
        photoUrl: "https://images.unsplash.com/photo-1517420704952-d9f39e95b43e?w=800&auto=format&fit=crop&q=60",
        remarks: "Replaced 40W LED fixture, fixed line wire contact, and verified illuminating angle with team.",
        resolvedAt: getDateAgo(2),
        officerName: "Anita Behera (Electrical Dept)",
      },
      citizenVerification: "pending",
      reopenedCount: 0,
      supporterIds: ["cit-106", "cit-150"],
      upvoteCount: 6,
    },
  ];
}
